### ISSUE TITLE
[RMS-002] GitHub Actions & sbt-release設定

### ISSUE THREAD

**Issue by takapi327** [takapi327/real-estate-sales-contract-management-system#4]
# GitHub Actions & sbt-release設定
# GitHub Actions Tag設定
### sbt-release
[sbt-release](https://github.com/sbt/sbt-release)に記載されている最新のバージョンでインストールを行います。
```
### version.sbt
プロジェクトルート直下に、version.sbtファイルを作成します。
ファイルには、下記のように最初のバージョンを設定します。
```
version in ThisBuild := "1.0.0-SNAPSHOT"
```sbt
addSbtPlugin("com.github.gseitz" % "sbt-release" % "1.0.13")
```

build.sbtに下記設定を追加
```sbt
import ReleaseTransformations._

releaseVersionBump := sbtrelease.Version.Bump.Bugfix

skip in publish := true

releaseProcess := Seq[ReleaseStep](
  inquireVersions,
  setReleaseVersion,
  commitReleaseVersion,
  tagRelease,
  releaseStepCommandAndRemaining("publish"),
  setNextVersion,
  commitNextVersion,
  pushChanges
)
```
### Github Actions設定
workflows以下のymlファイルに下記を記載
```yml
name: Deploy App

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run sbt release
        run: |
          git config --global user.email i-happy-go-lucky-life0001@ezweb.ne.jp
          git config --global user.name takapi327
          sbt "release with-defaults skip-tests"
```
### Slack連携
Github Actions設定に下記を追加
```yml
      - name: Notify deployment
        uses: 8398a7/action-slack@v3.8.0
        with:
          status: ${{ job.status }}
          author_name: デプロイ処理結果
          fields: repo,author,took,eventName,ref,workflow
          username: 'Slack Notification Action'
          icon_emoji: ':maruchan:'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
```
### デプロイ後実行結果
![image](https://user-images.githubusercontent.com/57429437/98259062-f76b7d80-1fc4-11eb-9899-c12fa1dc8c5d.png)

## 参考文献
[sbt-release](https://github.com/sbt/sbt-release)
[Github ActionsからSlackへ通知するのを良い感じにしたい](https://spinners.work/posts/github-actions-context/)
[Slack Incoming Webhook](https://github.com/marketplace/actions/slack-incoming-webhook)
[SlackのWebhook URL取得手順](https://qiita.com/vmmhypervisor/items/18c99624a84df8b31008)
[action-slack](https://action-slack.netlify.app/usage)
